### ISSUE TITLE
add @mburns back as a collaborator

### ISSUE THREAD

**Issue by mburns** [mburns/cookbook-libyaml#4]
@guilhem @redguide/owners - I didn't create a group/add myself when I transfered to the redguide org, so only the owners of redguide have commit access.

Please add me back as a collaborator. :smile:

Sidenote: Should each cookbook get an group, similar to how we have the [nodejs](/redguide/nodejs) repo setup?

**Comment by guilhem** [comment]
Hi @mburns,
I didn't see this cookbook before ^^
But I (really) don't know about keeping it in redguide.
It seems to be really specific and not at a good shape for now but you are working on it.

BTW, I'm giving you access to this cookbook ;)
